#!/bin/sh /etc/rc.common
# LINE Webhook Server init script

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/line-webhook-server
NAME=line_webhook

start_service() {
    local enabled
    config_load "$NAME"
    config_get_bool enabled main enabled 0

    [ "$enabled" -eq 0 ] && {
        echo "LINE Webhook is disabled"
        return 0
    }

    procd_open_instance
    procd_set_param command /usr/bin/python3 "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/line_webhook.pid
    procd_close_instance
}

stop_service() {
    echo "Stopping LINE Webhook Server"
}

service_triggers() {
    procd_add_reload_trigger "$NAME"
}

reload_service() {
    stop
    start
}
